---
- name: tomcat-server
  connection: local
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/tomcat-servers"
  roles:
    - selinux
    - tomcat

- name: deploy-clojure-collector
  connection: local
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/deploy-clojure"
  tasks:
    - name: Download Clojure WAR file
      command: wget http://d2io1hx8u877l0.cloudfront.net/2-collectors/clojure-collector/clojure-collector-1.1.0-standalone.war -O {{ warRemotePath }}/{{ warName }}

    - name: Unzip WAR file
      unarchive: src={{ warRemotePath }}/{{ warName }} dest=/opt/apache-tomcat-7.0.61/webapps copy=no mode=0755 owner=tomcat group=tomcat
      notify:
        - restart tomcat

    - name: Delete remote war file
      file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted

- name: ansible-pull-setup
  connection: local
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/ansible-pull"
  tasks:
    - name: Install ansible
      pip: name=ansible
    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751
    - name: Create crontab entry to clone/pull git repository
      template: src=templates/etc_cron.d_ansible-pull.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644
    - name: Create logrotate entry for ansible-pull.log
      template: src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
