---
- name: tomcat-server
  connection: local
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/tomcat-servers"
  roles:
    - selinux
    - tomcat
